project_id = "13012266-f8e7-402f-a745-cb64a7aadae2"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.explain-fit]
verify_jwt = false

[functions.validate-supplier]
verify_jwt = false
